//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EHkspenriment2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прайс.
    /// </summary>
    // *** Start programmer edit section *** (Прайс CustomAttributes)

    // *** End programmer edit section *** (Прайс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПрайсE", new string[] {
            "Цена as \'Цена\'",
            "СписокУслуг as \'Список услуг\'",
            "СписокУслуг.Имя as \'Имя\'"}, Hidden=new string[] {
            "СписокУслуг.Имя"})]
    [MasterViewDefineAttribute("ПрайсE", "СписокУслуг", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("ПрайсL", new string[] {
            "Цена as \'Цена\'",
            "СписокУслуг.Имя as \'Имя\'"})]
    public class Прайс : ICSSoft.STORMNET.DataObject
    {
        
        private double fЦена;
        
        private IIS.EHkspenriment2.СписокУслуг fСписокУслуг;
        
        // *** Start programmer edit section *** (Прайс CustomMembers)

        // *** End programmer edit section *** (Прайс CustomMembers)

        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Прайс.Цена CustomAttributes)

        // *** End programmer edit section *** (Прайс.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Прайс.Цена Get start)

                // *** End programmer edit section *** (Прайс.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Прайс.Цена Get end)

                // *** End programmer edit section *** (Прайс.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прайс.Цена Set start)

                // *** End programmer edit section *** (Прайс.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Прайс.Цена Set end)

                // *** End programmer edit section *** (Прайс.Цена Set end)
            }
        }
        
        /// <summary>
        /// Прайс.
        /// </summary>
        // *** Start programmer edit section *** (Прайс.СписокУслуг CustomAttributes)

        // *** End programmer edit section *** (Прайс.СписокУслуг CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокУслуг"})]
        [NotNull()]
        public virtual IIS.EHkspenriment2.СписокУслуг СписокУслуг
        {
            get
            {
                // *** Start programmer edit section *** (Прайс.СписокУслуг Get start)

                // *** End programmer edit section *** (Прайс.СписокУслуг Get start)
                IIS.EHkspenriment2.СписокУслуг result = this.fСписокУслуг;
                // *** Start programmer edit section *** (Прайс.СписокУслуг Get end)

                // *** End programmer edit section *** (Прайс.СписокУслуг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прайс.СписокУслуг Set start)

                // *** End programmer edit section *** (Прайс.СписокУслуг Set start)
                this.fСписокУслуг = value;
                // *** Start programmer edit section *** (Прайс.СписокУслуг Set end)

                // *** End programmer edit section *** (Прайс.СписокУслуг Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПрайсE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрайсE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрайсE", typeof(IIS.EHkspenriment2.Прайс));
                }
            }
            
            /// <summary>
            /// "ПрайсL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрайсL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрайсL", typeof(IIS.EHkspenriment2.Прайс));
                }
            }
        }
    }
}
